[package]
name = "verifier_api"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework và Async toolkit
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Thư viện lõi dùng chung trong Workspace
core = { path = "../core" }