[package]
name = "prover_client"
version = "0.1.0"
edition = "2021"

[dependencies]
# Giao tiếp HTTP với Verifier API
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Import thư viện lõi của Workspace
core = { path = "../core" }