[package]
name = "data_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
# Dùng để sinh dữ liệu và hash ngẫu nhiên
rand = "0.8.5"
# Serialize dữ liệu ra JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Định dạng hex cho Bitcoin mock hashes
hex = "0.4.3"
core_primitives = { path = "../core_primitives" }